### ISSUE TITLE
create a pull request templates in a .github folder 

### ISSUE THREAD

**Issue by jzandag** [jzandag/recipe-app#1]
comment here if you want to be assigned :))

**Comment by Neeraj-2307** [comment]
Hi I am new to github. Can I contribute?

**Comment by jzandag** [comment]
yes. Ill assign this to you :) good luck!

**Comment by Neeraj-2307** [comment]
thanks. any specifics for pull request template?

**Comment by jzandag** [comment]
the user should be able to pick if
//bug fix
//new feature
//documentation changes
//refactor old code 
//changes will impact other code

and put a separate area for the description of the pull request. That would be all
